### ISSUE TITLE
Push Notification on Battery Saver Mode

### ISSUE THREAD

**Issue by sh0umik** [pushy-me/pushy-flutter#1]
I am Using OnePlus 6t and the flutter sdk for pushy works fine except when i turn on the battery saver mode. It goes into sleep and i get all the notification at once when i turn off the battery saver mode.

Is there ary way around this ? Receiving notifications while in battery saver mode ? Firebase seems to do it.

**Comment by pushy-me** [comment]
Hi @sh0umik,
Nice to connect with you. I'd be glad to assist with you inquiry.

Chinese-based devices including OnePlus may not receive notifications after your app is swiped away from the recent apps menu, goes to background, during power saving mode, or after a device reboot due to custom power saving features which affect Firebase Cloud Messaging as well.

Most notably, Chinese devices from the following manufacturers include custom power-saving restrictions which may hinder background notification delivery for your app:

Xiaomi
Huawei
OnePlus
Samsung
Oppo
Vivo
Asus
Sony
Honor

Unfortunately, since these power saving mechanisms also affect FCM, it is not a Pushy-specific issue, and the recommended solution is to instruct the user to whitelist your app from the respective manufacturer's power saving mechanism in the phone settings. The instructions for doing this vary from one manufacturer to another.

Read more about this issue:
https://dontkillmyapp.com/problem

I apologize for this inconvenience introduced by Chinese device manufacturers.
