### ISSUE TITLE
Is there any way to show Notification when app is background or killed

### ISSUE THREAD

**Issue by M6268** [pushy-me/pushy-flutter#10]
When the app is swiped away from the recent list or it gets killed the notification not getting received or showed.

Is there any workaround to achieve background listening method over come this

**Comment by pushy-me** [comment]
Hi @M6268,
Thanks for your report. We'd be glad to help you investigate this issue further.

If you could please provide the following information about the device experiencing this issue, that would be great:
1) Device manufacturer
2) Device model name
3) Android OS version

**Comment by M6268** [comment]
Redmi
K20 pro
Android 10 MIUI 12

**Comment by pushy-me** [comment]
Hi @M6268,
Thanks for the report. We've issued a fix so that your app will be able to receive notifications on Xiaomi devices after it goes to background or is swiped away from recent apps.

Please update the [Pushy Flutter SDK](https://pushy.me/docs/additional-platforms/flutter) in your app by editing the `pubspec.yaml` in the root directory of your project and updating the `pushy_flutter` package version to `1.0.12`:
```
pushy_flutter: 1.0.12
```

Then, run `flutter pub get` to fetch the new SDK. Run your app and let us know if the issue is fixed!

---

As for your other inquiry about your foreground notification being overriden, our SDK uses notification ID "1" when it issues the notification:

```
notificationManager.notify(1, builder.build());
```

For your foreground notification, please pass a different notification ID than 1 when invoking `NotificationManager`, and it should fix the notification override issue.

Please let us know if there's anything else I can help with.

**Comment by engrjabi** [comment]
Hi, I'm also encountering the issue on the notification not being shown if the app is closed. does the flutter sdk already handle the sending of notifications even if the app is closed? I checked the source code and it seems it is using the flutter isolate library
